spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneShop
    password: phone123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update